### 5. DETECÇÃO DE OUTLIER | TAXA DE RISCO

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [33]:
df_base_geral = pd.read_csv("base_pronta.csv", sep=";")

In [25]:
df_if = pd.read_csv("base_isolation_forest.csv", sep=";")

In [26]:
df_if.shape

(449, 20)

In [27]:
df_if[["CO_ENTIDADE", "NOME_ENTIDADE", "IF_resultado"]]

     CO_ENTIDADE                                  NOME_ENTIDADE  IF_resultado
0       52001199     COLEGIO ESTADUAL DE SAO MIGUEL DO ARAGUAIA            -1
1       52029220           ESCOLA ESTADUAL JOSE MANOEL DA SILVA            -1
2       52012620     COLEGIO ESTADUAL FELISMINA CARDOSO BATISTA            -1
3       52069460                  ESCOLA MUNICIPAL DE NOVA VILA            -1
4       52100928                       IF GOIANO - CAMPUS POSSE            -1
..           ...                                            ...           ...
444     52087930                      CMEI MARCIA LORENA MENDES            -1
445     52067343  COLEGIO ESTADUAL DEPUTADO JOSE ALVES DE ASSIS            -1
446     52091937                    EDUCANDARIO SANTA TEREZINHA            -1
447     52003396                  COLEGIO ESTADUAL WALTER ENGEL            -1
448     52076032                         ESC MUL SABINO MAMEDIO            -1

[449 rows x 3 columns]

In [28]:
df_tr_escolas = pd.read_excel('Base_TR\BRASIL_TR_2020_21_ajustada_escola.xlsx')

In [29]:
df_tr_escolas[["CO_ENTIDADE", "NOME_ENTIDADE", "TAXA_RISCO_ENT"]]

,CO_ENTIDADE,NOME_ENTIDADE,TAXA_RISCO_ENT
0,52086038,COLEGIO ESTADUAL RAFAEL DE SOUZA BARBOSA,5
1,52104494,ESCOLA CEMYR,9
2,52105750,COLEGIO GRADUAL,6
3,52012387,ESCOLA ESTADUAL DOUTOR GERSON DE FARIA PEREIRA,5
4,52075680,ESC MUL 1º GRAU EMILIO ANTUNES DE FRANCA,5
...,...,...,...
121,52099415,ESCOLA CAMINHO DO SABER,6
122,52103943,ESCOLA EVANGELICA LAPIS NA MAO,9
123,52104907,CENTRO EDUCACIONAL ELOHIM,8
124,52105644,ESCOLA ADVENTISTA DE VALPARAISO,9
125,52064107,ESCOLA ESTADUAL ZENAIDE CAMPOS RORIZ,5

In [30]:
df_compara_is_tr = df_if.merge(df_tr_escolas, on='CO_ENTIDADE')

In [34]:
print("Ocorrências similares na base Isolation Forest e Taxa de risco:", df_compara_is_tr.shape[0])

Ocorrências similares na base Isolation Forest e Taxa de risco: 13

In [36]:
df_apresenta = df_base_geral.merge(df_compara_is_tr, on='CO_ENTIDADE')

In [38]:
df_apresenta.columns.tolist()

['CO_UF_x',
 'UF',
 'SIG_UF_x',
 'CO_MUNICIPIO',
 'MUNICIPIO_x',
 'CO_MESORREGIAO_x',
 'CO_MICRORREGIAO_x',
 'CO_ENTIDADE',
 'NOME_ENTIDADE',
 'POPULACAO_ESTIMADA_x',
 'N_MATRICULA_MUN_19_x',
 'N_MATRICULA_ENT_19_x',
 'N_MATRICULA_INTEGRAL_ENT_19_x',
 'N_MATRICULA_MUN_20_x',
 'N_MATRICULA_ENT_20_x',
 'N_MATRICULA_INTEGRAL_ENT_20_x',
 'SCORE_MAT_MUN_20_19_x',
 'SCORE_MAT_ENT_20_19_x',
 'SCORE_MAT_INTEGRAL_ENT_20_19_x',
 'CO_UF_y',
 'UF_x',
 'SIG_UF_y',
 'CO_MUNICIPIO_x',
 'MUNICIPIO_y',
 'CO_MESORREGIAO_y',
 'CO_MICRORREGIAO_y',
 'NOME_ENTIDADE_x',
 'POPULACAO_ESTIMADA_y',
 'N_MATRICULA_MUN_19_y',
 'N_MATRICULA_ENT_19_y',
 'N_MATRICULA_INTEGRAL_ENT_19_y',
 'N_MATRICULA_MUN_20_y',
 'N_MATRICULA_ENT_20_y',
 'N_MATRICULA_INTEGRAL_ENT_20_y',
 'SCORE_MAT_MUN_20_19_y',
 'SCORE_MAT_ENT_20_19_y',
 'SCORE_MAT_INTEGRAL_ENT_20_19_y',
 'IF_resultado',
 'CODIGO_UF',
 'UF_y',
 'CO_MUNICIPIO_y',
 'NOME_MUNICIPIO',
 'NOME_ENTIDADE_y',
 'TAXA_RISCO_ENT']

In [41]:
df_apresenta[[
 'UF',
 'SIG_UF_x',
 'MUNICIPIO_x',
 'CO_MESORREGIAO_x',
 'CO_MICRORREGIAO_x',
 'CO_ENTIDADE',
 'NOME_ENTIDADE',
 'POPULACAO_ESTIMADA_x',
    
 'N_MATRICULA_MUN_19_x',
 'N_MATRICULA_MUN_20_x',

 'SCORE_MAT_MUN_20_19_x',
      
 'N_MATRICULA_ENT_19_x',
 'N_MATRICULA_ENT_20_x',
 
 'SCORE_MAT_ENT_20_19_x',
 
 'IF_resultado',
 
 'TAXA_RISCO_ENT']]

,UF,SIG_UF_x,MUNICIPIO_x,CO_MESORREGIAO_x,CO_MICRORREGIAO_x,CO_ENTIDADE,NOME_ENTIDADE,POPULACAO_ESTIMADA_x,N_MATRICULA_MUN_19_x,N_MATRICULA_MUN_20_x,SCORE_MAT_MUN_20_19_x,N_MATRICULA_ENT_19_x,N_MATRICULA_ENT_20_x,SCORE_MAT_ENT_20_19_x,IF_resultado,TAXA_RISCO_ENT
0,Goias,GO,Matrinchã,5201,52002,52004260,COLEGIO ESTADUAL ALCIDES RAMOS JUBE,4351,833,840,1.008403,76,67,0.881579,-1,7
1,Goias,GO,Cavalcante,5202,52005,52014428,ESC MUL DONA JOANA PEREIRA DAS VIRGENS,9709,2620,2325,0.887405,6,10,1.666667,-1,5
2,Goias,GO,Cavalcante,5202,52005,52013189,ESC MUL TERRA VERMELHA,9709,2620,2325,0.887405,5,3,0.600000,-1,5
3,Goias,GO,São Simão,5205,52018,52068420,COLEGIO ESTADUAL DE SAO SIMAO,20645,3837,3516,0.916341,163,171,1.049080,-1,5
4,Goias,GO,Novo Gama,5204,52012,52047172,CAIC NOVO GAMA,115711,20192,19788,0.979992,176,445,2.528409,-1,9
5,Goias,GO,Aparecida de Goiânia,5203,52010,52104257,COLEGIO ESTADUAL MICHELLE DO PRADO RODRIGUES,578179,116323,118693,1.020374,920,376,0.408696,-1,5
6,Goias,GO,Campos Verdes,5202,52004,52006638,COLEGIO ESTADUAL EDMUNDO ROCHA,2141,929,939,1.010764,204,492,2.411765,-1,5
7,Goias,GO,Itapaci,5203,52006,52017354,CENTRO DE ENSINO EM PERIODO INTEGRAL SANTA TER...,22981,4919,4846,0.985160,104,300,2.884615,-1,7
8,Goias,GO,Aragarças,5201,52003,52004686,CENTRO DE ENSINO EM PERIODO INTEGRAL THALES PO...,20118,3637,3715,1.021446,204,181,0.887255,-1,5
9,Goias,GO,Planaltina,5204,52012,52104354,COLEGIO ESTADUAL DOUTOR DIRCEU FERREIRA DE ARAUJO,89918,25429,25086,0.986511,157,367,2.337580,-1,6
10,Goias,GO,Anicuns,5203,52009,52028518,CENTRO DE ENSINO EM PERIODO INTEGRAL PROFESSOR...,21850,4142,3560,0.859488,84,224,2.666667,-1,6
11,Goias,GO,Goiânia,5203,52010,52104028,ESCOLA MUNICIPAL PROFESSORA LOUSINHA,1516113,279830,276809,0.989204,126,283,2.246032,-1,6
12,Goias,GO,Ipameri,5205,52017,52066053,CENTRO DE ENSINO EM PERIODO INTEGRAL MICHELE S...,26985,6135,5939,0.968052,124,202,1.629032,-1,8

In [44]:
df_apresenta[[
 'UF',
 'SIG_UF_x',
 'MUNICIPIO_x',
 'CO_MESORREGIAO_x',
 'CO_MICRORREGIAO_x',
 'CO_ENTIDADE',
 'NOME_ENTIDADE',
 'POPULACAO_ESTIMADA_x',
    
 'N_MATRICULA_MUN_19_x',
 'N_MATRICULA_MUN_20_x',

 'SCORE_MAT_MUN_20_19_x',
      
 'N_MATRICULA_ENT_19_x',
 'N_MATRICULA_ENT_20_x',
 
 'SCORE_MAT_ENT_20_19_x',
 
 'IF_resultado',
 
 'TAXA_RISCO_ENT']].to_csv('avalia_IF_TR.csv', sep=';', index = False)